### ISSUE TITLE
Access to lead platform: not user foun with this email

### ISSUE THREAD

**Issue by beateruel** [Horizon-LEAD/lead-platform-doc#1]
I have not received any invitation to the LEAD platform after the email sent by Dimitra concerning the LL5 Oslo.

**Comment by andalexo** [comment]
Invitation sent; could you please check again at your zlc.edu email ? 
Please also check the junk folder although I have tested it with gmail, outlook, company and university mails and it went through. Still, in some cases apparently it failed so let us know !

**Comment by beateruel** [comment]
I checked the spam this morning and I could access it.
Thanks!
