### ISSUE TITLE
Visum-copert issue

### ISSUE THREAD

**Issue by HorvathAdrian** [Horizon-LEAD/lead-platform-doc#13]
manual__2023-06-09T09:02:54.849161+00:00

**Comment by andalexo** [comment]
I see that there was an issue with the format of the provided weather csv.
I will send you an email so that we sync and start the VISUM server so that we debug both the VISUM->COPERT and VISUM->EVCO2 scenarios.

**Comment by andalexo** [comment]
Issue resolved; example execution shared.
